name: Simple CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Code coverage
      run: npm run coverage

    - name: Code analysis
      run: npm run lint

    - name: Deploy to staging
      run: echo "Deploying to staging environment"
      # Add your deployment script/commands here

    - name: Notify team on failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Build or deployment failed. Please check the logs."
